import Head from 'next/head'
import React from 'react'
import Contact from './Contact'
import MainPage from './MainPage'
import Navbar from './Navbar'
import Projects from './Projects'

const Layout = ({children} : any) => {
  return (
    <div>
      <Head>
        <link rel="shortcut icon" href="/assets/Chen_Logo.png" />
        <title>Welcome To Chen Homepage</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

        <main>
            {children}
        </main>
    </div>
  )
}

export default Layout