import Head from 'next/head'
import Image from 'next/image'
import MainPage from '../components/MainPage'
import Navbar from '../components/Navbar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Welcome To Chen Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Navbar></Navbar>
      <MainPage></MainPage>
    </div>
  )
}
